### ISSUE TITLE
Maquetación Pantallas 3 a 6 Stand Alone

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Siguit#2]
Fede, te cargo el ticket. Ya te pasé el wetransfer. COnfirmame si lo recibiste.

abrazo

**Comment by LeandroBraier** [comment]
Frenado esto por ahora, lo estamos corrigiendo. Cuando lo tengo listo te lo paso. abrazo

**Comment by FAAREIA** [comment]
Hola Lea, cuando puedas pasame la imagen esa que me mostraste ayer que tenia las flechitas.

Abrazo

**Comment by LeandroBraier** [comment]
Fede, ahí te subí el "Mapa del Sitio" de Siguit a la carpeta Siguit Maquetador. También te subí una imagen del Edificio de Siguit nueva para la pantalla 2.

De todas formas estoy actualizando el Script para que también te bases en eso. Mientras avanzo con eso, necesitaría que me mandes el resto de las landings de la semana 6 terminadas. Llegás para hoy?

**Comment by LeandroBraier** [comment]
Fede, va el feedback final de Eze:

PANTALLA 1: (la que tiene el video) OK.El BIENVENIDO esta en negrita,
cambiarlo ídem al resto de la typo. El logo ISS intentaría hacerlo un poco
mas grande.

PANTALLA 2: El botón de ATRAS, quizás es un poco confuso. No se entienda
cual es la función. Yo le pondría ³VOLVER² (EN TODAS LAS PANTALLAS DONDE
APARECE)

PANTALLA 3: OK

PANTALLA 4: (HABIENDO SELECCIONADO ³TODA LA PLANTA²) El titulo de esa
pantalla debería ser: ³Señale el desperfecto a reportar en toda la planta²

PANTALLA 5: (Habiendo seleccionado una planta) OK

PANTALLA 6: Ojo, seleccione en la pantalla anterior la oficina 45 y la
gráfica que me trae fue la de otra oficina. Habria que poner en gris (para
la demo) las que no estan seleccionables. O hacer los closeup de todas las
opciones clickeables de la demo. Para la versión demo, abriría todos los
ítems (ELECTRICIDAD, TELFONIA, MOBLIARIO, CERRAJERIA, OTROS, FALTA UNO MUY
IMPORTANTE²LIMPIEZA"para que puedan ser clickeables)
Al seleccionar un ítem, por ejemplo dentro de AIRE ACONDICIONADO - Perdida
de agua. Al seleccionarlo debería pintarse de rojo tambien. Siguiendo la
lógica de todo lo anterior.

PANTALLA 7: Cambiar texto: ³El reporte ha sido registrado y procederemos
ha resolver la situación² ³Déjanos tu nombre para cualquier consulta
adicional que necesitemos"

PANTALLA 8: EN el texto final, agregarle logo de ISS.

Muy bien esta quedando!!!

**Comment by FAAREIA** [comment]
http://www.benteveo.tv/_siguit/

Ojo que no abri todos los items que decia Eze, porque expondría mucho que a esa parte todavía le falta. Queda tosco que opciones se oculten, y que haya que apretar otra opción para mostarlas nuevamente. Lo de limpieza lo agregué en todos.

**Comment by LeandroBraier** [comment]
Genial quedó Fede! Por ahora estamos OK, cualquier cosa lo cambiamos a tu vuelta. 

Marce K, vos subís esta última versión al servidor de Siguit?

**Comment by FAAREIA** [comment]
=D joya

**Comment by LeandroBraier** [comment]
Marce, recibís este mail? Confirmame por favor. Necesito saber si ya está todo subido en Siguit.com y funcional. En tal caso, necesitaría que ya cargues también la Versión Intendente y ver cómo se despliegan en esa versión los desperfectos cargados en esta.

Llegás a tener algo para el lunes que viene?

abrazo

**Comment by mkreyness** [comment]
Si, pero no vi que me lo habias asignado, vi que le hablabas a Fede.

En siguit.com esta cargada la parte standalone, pero estoy trabajando 
sobre eso, quiere decir que a ratos puede funcionar, y a ratos no.
Ya esta grabando datos pero con valores fijos que no corresponden a las 
descripciones que yo tengo cargadas en mi base de datos, asi que primero 
tengo que ajustar eso.

No pase todavia la version intendente, ya que ademas todo eso lo tengo 
que tomar como template pero modificar bastante.
Si, mi intencion es que este todo mostrable para el lunes 5.
Igual ESE dia estoy muy complicado, si tenemos que juntarnos que no sea 
ese lunes plis.
