### ISSUE TITLE
Consulta técnica

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Siguit#4]
Fede, consulta al margen. Podemos usar este tipo de iconos animados dentro de la web de Siguit?

Digo, los animamos en AE con un template como el de abajo y lo exportamos en un formato que pueda ejecutarse en HTML5. Es posible?
http://videohive.net/item/237-animated-icons/9564055?WT.oss_phrase=credits&WT.oss_rank=7&WT.z_author=balazsrenata&WT.trending=trending&WT.ac=search_list

**Comment by FAAREIA** [comment]
Si se puede, pero hay que ejecutarlo en el momento exacto. Sería un gif me imagino.

**Comment by LeandroBraier** [comment]
Genial
