### ISSUE TITLE
Diseño de Mail de Delegación de Tareas

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Siguit#7]
Fede, te paso el texto que iría:

Roberto Marquez, Intendente de ISS en tu empresa, te ha delegado la siguiente tarea:

TICKET 62- REPARACIÓN DE AIRE ACONDICIONADO en PISO 1- OFICINA 28

Deberías resolver esta tarea en el lapso de 3 horas. Por favor, confirmá que recibiste este mail haciendo clic en "OK" y, una vez que hayas llevado a cabo el encargo correspondiente, seleccioná la opción "RESUELTO".

BOTÓN 1: "OK. RECIBIDO."

BOTÓN 2: "RECHAZAR"

BOTÓN 3: "RESUELTO"

Muchas gracias.

**Comment by FAAREIA** [comment]
http://siguit.com/_siguit-admin/mailing/informe.html

**Comment by mkreyness** [comment]
```
Quedamos en que los botones igual no hagan nada por ahora, no ?
El "aceptar" en realidad es muy probable que no tenga que hacer
nada.
El rechazo se podria manejar "desdelegando" la tarea, eso no es
complicado, volveria a "reportado".
Pero nos faltaria tener un estado intermedio entre delegado/demorado
y ok que seria "a verificar".
Salvo que hagamos que fuerce el "ok".
En una version mas completa, la tarea podria decir si requiere
revision o no, y el "resuelto" podria marcar "ok" o "a revisar"
segun eso.


El 17/01/2015 a las 12:18, Federico
  Arena escribió:


  http://siguit.com/_siguit-admin/mailing/informe.html
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by LeandroBraier** [comment]
Para el demo no hace falta que funcionen los botones del mail.

Más allá de eso, para la versión más completa agregaría un estado que diga
"Terminado" y cambiaría el status de "OK" por "Resuelto", que
correspondería con el A verificar que decís.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-01-18 22:09 GMT-03:00 mkreyness notifications@github.com:
